Fix quoting error in error_exit
Fix a quoting error in which a literal 0 would be printed instead of the
$0 variable

diff --git a/shshare b/shshare
--- a/shshare
+++ b/shshare
@@ -30,7 +30,7 @@ finish_screencast() {
 trap finish_screencast SIGUSR1
 
 error_exit() {
-	echo "$(basename $"0"): ${1:-"Unknown error"}" 1>&2
+	echo "$(basename "$0"): ${1:-"Unknown error"}" 1>&2
 	exit $"2"
 }
 
